plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
  - auslastung.md
  - mac.md
  - windows.md 
  - disable_video.md
  - netzwerk.md
