plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
  - auslastung.md
  - mac.md
  - windows.md 


theme: jekyll-theme-cayman